export const FETCH_UNIVERSITY = "FETCH_UNIVERSITY";
export const FETCH_ID = "FETCH_ID";
export const FETCH_STUDENT = "FETCH_STUDENT";
export const FETCH_ALL_COURSES = "FETCH_ALL_COURSES";
export const FETCH_COMPANY = "FETCH_COMPANY";
export const FETCH_ALL_UNIVERSITIES = "FETCH_ALL_UNIVERSITIES";
